# Generated by Django 6.0.5 on 2026-06-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizaciongps',
            name='camion',
        ),
        migrations.AddField(
            model_name='actualizaciongps',
            name='placa_camion',
            field=models.CharField(default='UV2026TX', max_length=8),
            preserve_default=False,
        ),
    ]
