# Generated by Django 6.0.5 on 2026-06-15 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="El identificador debe iniciar con 'BN-' seguido de 6 a 10 caracteres alfanuméricos.", regex='^BN-[A-Z0-9]{6,10}$')])),
                ('descripcion', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('estatus', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('INCIDENCIA', 'Con Incidencia')], default='REGISTRADO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bienes', to='clientes.cliente')),
                ('direccion_entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bienes_a_entregar', to='clientes.direccion')),
                ('direccion_recoleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bienes_a_recolectar', to='clientes.direccion')),
            ],
        ),
    ]
