# Generated by Django 6.0.5 on 2026-06-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_TRANSITO', 'En Tránsito'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=20)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='bienes.bien')),
            ],
        ),
    ]
