# Generated by Django 6.0.5 on 2026-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0002_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
