# Generated by Django 6.0.5 on 2026-06-15 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El identificador debe ser alfanumérico en mayúsculas, entre 5 y 15 caracteres.', regex='^[A-Z0-9]{5,15}$')])),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="El identificador de dirección debe iniciar con 'DIR-' seguido de 4 a 8 números.", regex='^DIR-[0-9]{4,8}$')])),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener exactamente 5 dígitos.', regex='^\\d{5}$')])),
                ('tipo', models.CharField(choices=[('ORIGEN', 'Origen / Recolección'), ('DESTINO', 'Destino / Entrega'), ('RESGUARDO', 'Resguardo Interno')], max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
