# Generated by Django 6.0.5 on 2026-06-15 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nombre_usuario', models.CharField(help_text='Para conservar el registro si el usuario es eliminado', max_length=150)),
                ('rol', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error del Sistema')], max_length=20)),
                ('descripcion', models.TextField()),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Registros de Bitácora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
